<?php

declare(strict_types=1);

use LSNepomuceno\LaravelA1PdfSign\Contracts\SignatureValidator;
use LSNepomuceno\LaravelA1PdfSign\Support\Files;
use LSNepomuceno\LaravelA1PdfSign\Validation\Pkcs7Reader;

/**
 * Every signed artefact in the repository was signed by the certificate the
 * repository holds.
 *
 * This is the check that was missing. Regenerating `samples/` replaced the
 * certificate, since `poc/sign-samples.php` minted a fresh identity on every
 * run, and `tests/Resources/foreign-signed.pdf` was left signed by the previous
 * one: fingerprint `163d4764…` against the `5ab3345c…` the directory then held.
 *
 * **No test failed.** `ForeignSignatureTest` reads the document rather than the
 * anchor, so it stayed green while the file's own docblock had become false. It
 * was found by comparing fingerprints by hand, which is not a process.
 *
 * It also broke something two steps away without failing:
 * `CertificationEnforcementTest` takes its trust anchor from the sample
 * certificate, so the tampered fixture would have gone on passing **for the
 * wrong reason**, an untrusted signature being INVALID too.
 *
 * **Not a byte comparison.** Signed output is not reproducible: the signing
 * time and the padding differ per run, so "regenerate and diff" can never be
 * green twice. The gate is identity
 * (docs/decisions/0036-the-signed-artefacts-are-reproducible.md).
 */

/**
 * The SHA-256 fingerprints of every certificate embedded in a signed document.
 *
 * @return list<string>
 */
function certificateFingerprintsIn(string $path): array
{
    $contents = Files::read($path);
    $reader = new Pkcs7Reader();
    $found = [];

    foreach (app(SignatureValidator::class)->validate($contents)->signatures as $signature) {
        // The DER embedded in the signature, read by the package's own ASN.1
        // walker rather than by shelling out. A fingerprint over the whole
        // certificate is the identity: the serial of a throwaway bundle is 0
        // and its common name is the same for every one ever generated, so
        // neither can tell two of them apart.
        foreach ($reader->certificates((string) $signature->rawContents) as $der) {
            $fingerprint = openssl_x509_fingerprint($der, 'sha256');

            if (is_string($fingerprint)) {
                $found[] = $fingerprint;
            }
        }
    }

    return array_values(array_unique($found));
}

/**
 * Every committed document that carries a signature.
 *
 * @return array<string, string>
 */
function signedArtefacts(): array
{
    $samples = glob(dirname(__DIR__) . '/samples/*.pdf');

    $paths = array_merge(
        $samples === false ? [] : $samples,
        [dirname(__DIR__) . '/tests/Resources/certified-then-modified.pdf'],
    );

    $artefacts = [];

    foreach ($paths as $path) {
        $artefacts[str_replace(dirname(__DIR__) . '/', '', $path)] = $path;
    }

    return $artefacts;
}

it('signs every committed artefact with the certificate the repository holds', function (string $path) {
    $expected = openssl_x509_fingerprint(Files::read(dirname(__DIR__) . '/samples/certificate.pem'), 'sha256');

    expect(certificateFingerprintsIn($path))->toContain($expected);
})->with(signedArtefacts());

it('has artefacts to check, so an empty list cannot pass for a green gate', function () {
    // A glob that silently returns nothing would make the dataset above run no
    // cases at all and report success.
    expect(signedArtefacts())->toHaveCount(12);
});

it('signs the foreign fixture with the same certificate, though another tool wrote it', function () {
    // The file that drifted. pyHanko produced it, so it is not regenerated by
    // poc/sign-samples.php, which is exactly why it went unnoticed.
    $expected = openssl_x509_fingerprint(Files::read(dirname(__DIR__) . '/samples/certificate.pem'), 'sha256');

    expect(certificateFingerprintsIn(resource('foreign-signed.pdf')))->toContain($expected);
});

it('holds a certificate that has not expired', function () {
    // Reusing the committed certificate makes its expiry a property of the
    // repository rather than of the last run. When this fails, every signed
    // artefact is regenerated together, which is the trade written down in the
    // decision record.
    $parsed = openssl_x509_parse(Files::read(dirname(__DIR__) . '/samples/certificate.pem'));

    expect($parsed)->toBeArray();

    /** @var array{validTo_time_t: int} $parsed */
    expect($parsed['validTo_time_t'])->toBeGreaterThan(time());
});
