export { default as NavBar } from './NavBar.vue'
export { default as HeaderTitle } from './HeaderTitle.vue'
export { default as MainContent } from './MainContent.vue'
export { default as SideBar } from './SideBar.vue'
export { default as ErrorsAlert } from './ErrorsAlert.vue'
